version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn conductor.core.asgi:app --host 127.0.0.1 --port 8080 --workers 1
      "
    volumes:
      - .:/conductor
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod --quiet --logpath /dev/null
